-- =============================================================================
-- H2 建表脚本（与当前 JPA 实体对齐，用于在无 ddl-auto 或全新库时手工初始化）
-- 使用方式：在目标库先执行本文件，再执行 data.sql。
-- 若库已由 Spring Boot（spring.jpa.hibernate.ddl-auto=update）建表，可跳过本文件。
-- =============================================================================

DROP TABLE IF EXISTS system_logs;
DROP TABLE IF EXISTS stock_logs;
DROP TABLE IF EXISTS finance_records;
DROP TABLE IF EXISTS loan_repayments;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS reimbursements;
DROP TABLE IF EXISTS project_documents;
DROP TABLE IF EXISTS change_orders;
DROP TABLE IF EXISTS contracts;
DROP TABLE IF EXISTS payment_plan_items;
DROP TABLE IF EXISTS milestones;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS suppliers;

CREATE TABLE suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  contact_person VARCHAR(64),
  contact_phone VARCHAR(32),
  bank_info CLOB
);

CREATE TABLE departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  parent_id BIGINT
);

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(255),
  built_in BOOLEAN NOT NULL
);

CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL UNIQUE,
  manager_id VARCHAR(255) NOT NULL,
  contract_amount DECIMAL(15, 2) NOT NULL,
  received_amount DECIMAL(15, 2),
  material_cost DECIMAL(15, 2),
  labor_cost DECIMAL(15, 2),
  other_cost DECIMAL(15, 2),
  total_budget DECIMAL(15, 2),
  status VARCHAR(255) NOT NULL,
  progress INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(128) NOT NULL,
  role VARCHAR(32) NOT NULL,
  enabled BOOLEAN NOT NULL,
  department_id BIGINT
);

CREATE TABLE inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  spec VARCHAR(255),
  unit VARCHAR(255),
  price DECIMAL(19, 2),
  quantity INTEGER,
  threshold INTEGER
);

CREATE TABLE milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  plan_date DATE NOT NULL,
  actual_date DATE,
  status VARCHAR(255) NOT NULL,
  project_id BIGINT NOT NULL
);

CREATE TABLE payment_plan_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  plan_date DATE NOT NULL,
  plan_amount DECIMAL(15, 2) NOT NULL,
  received_amount DECIMAL(15, 2) NOT NULL,
  status VARCHAR(32) NOT NULL
);

CREATE TABLE contracts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  contract_no VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  contract_amount DECIMAL(15, 2) NOT NULL,
  signed_date DATE NOT NULL,
  settlement_status VARCHAR(32) NOT NULL,
  monitoring_status VARCHAR(32) NOT NULL,
  remark CLOB,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE change_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  reason VARCHAR(256) NOT NULL,
  amount DECIMAL(15, 2) NOT NULL,
  status VARCHAR(32) NOT NULL,
  approver VARCHAR(64),
  approval_date DATE,
  approval_note CLOB,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE project_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL,
  name VARCHAR(256) NOT NULL,
  link VARCHAR(1024),
  remark CLOB,
  source VARCHAR(32),
  created_at TIMESTAMP
);

CREATE TABLE loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT,
  department_id BIGINT,
  borrower VARCHAR(64) NOT NULL,
  amount DECIMAL(15, 2) NOT NULL,
  date DATE NOT NULL,
  status VARCHAR(32) NOT NULL,
  creator VARCHAR(64) NOT NULL,
  approver VARCHAR(64),
  approval_date DATE,
  approval_note CLOB,
  reason CLOB,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE loan_repayments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id BIGINT NOT NULL,
  amount DECIMAL(15, 2) NOT NULL,
  date DATE NOT NULL,
  status VARCHAR(32) NOT NULL,
  creator VARCHAR(64) NOT NULL,
  approver VARCHAR(64),
  approval_date DATE,
  approval_note CLOB,
  note CLOB,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE reimbursements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT,
  department_id BIGINT,
  applicant VARCHAR(64) NOT NULL,
  amount DECIMAL(15, 2) NOT NULL,
  category VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  date DATE NOT NULL,
  creator VARCHAR(64) NOT NULL,
  approver VARCHAR(64),
  approval_date DATE,
  approval_note CLOB,
  description CLOB,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE finance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  amount DECIMAL(15, 2) NOT NULL,
  project_id BIGINT,
  payment_plan_item_id BIGINT,
  supplier_id BIGINT,
  department_id BIGINT,
  cost_type VARCHAR(20),
  status VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  creator VARCHAR(255) NOT NULL,
  description CLOB,
  approver VARCHAR(255),
  approval_date DATE,
  approval_note CLOB,
  reversal_of_id BIGINT,
  is_reversal BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE stock_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  item_id BIGINT NOT NULL,
  qty INTEGER NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  project_id BIGINT,
  supplier_id BIGINT,
  status VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  creator VARCHAR(255) NOT NULL,
  note CLOB,
  approver VARCHAR(255),
  approval_date DATE,
  approval_note CLOB,
  reversal_of_id BIGINT,
  is_reversal BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  time TIMESTAMP(6) NOT NULL,
  operator VARCHAR(255) NOT NULL,
  action VARCHAR(255) NOT NULL,
  detail CLOB
);
